## MY first Notbook

In [13]:
# below code just introduction
a=5
b=2
c=a%b
d="gc university"
print("safyan")
print(a)
print(b)
print(c)
print(d)

safyan
5
2
1
gc university


In [17]:
a=[10,20,30,40,50]
print(a)
print(a[3])

[10, 20, 30, 40, 50]
40


In [22]:
b=[100,200,300,400,500]
c=a[4]+b[1]
print(c)


250


In [29]:
def Grade(marks):
    if(marks>90):
        print("A+")
    elif(marks>85):
        print("A")
    elif(marks>80):
        print("B+")
    elif(marks>70):
        print("B")
    else:
        print("Fail")

In [31]:
Grade(60)

Fail


In [26]:
# for loop
def table(n):
    for i in range(1,11,1):
        print(i,"*",n, "=",i*n)
    

In [28]:
table(9)

1 * 9 = 9
2 * 9 = 18
3 * 9 = 27
4 * 9 = 36
5 * 9 = 45
6 * 9 = 54
7 * 9 = 63
8 * 9 = 72
9 * 9 = 81
10 * 9 = 90


In [40]:
import numpy as np

In [50]:
a=np.array([[1,2,3],[4,5,6],[9,10,20]])

In [55]:
a.size

9

In [56]:
b=np.zeros((3,3))

In [57]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
b=np.ones((3,3))

In [59]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
b=np.eye(3,3)

In [62]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
a=np.array([[1,2,3],[4,5,6],[9,10,20]])

In [66]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 9, 10, 20]])

In [67]:
a[2,1]

np.int64(10)

In [68]:
a=np.arange(1,10)

In [69]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a=np.arange(1,10,2)

In [71]:
a

array([1, 3, 5, 7, 9])

In [72]:
a=np.array([[1,2,3],[4,5,6],[9,10,20]])

In [73]:
b=np.array([[10,20,30],[40,50,60],[90,100,200]])

In [75]:
c=a+b

In [76]:
c

array([[ 11,  22,  33],
       [ 44,  55,  66],
       [ 99, 110, 220]])

In [78]:
c=np.matmul(a,b)

In [79]:
c

array([[ 360,  420,  750],
       [ 780,  930, 1620],
       [2290, 2680, 4870]])

In [82]:
a=a+3

In [83]:
a


array([[ 4,  5,  6],
       [ 7,  8,  9],
       [12, 13, 23]])